apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes: 
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-pv-claim
      containers:
        - name: pingpong
          image: hugonaing/ping-pong:v2.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts: 
            - name: shared-storage
              mountPath: /usr/src/app/files
