apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes: 
      - name: shared-storage
        persistentVolumeClaim: 
          claimName: shared-pv-claim
      containers:
        - name: todo-app
          image: hugonaing/to-do-app:1.8
          imagePullPolicy: Always
          ports: 
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
