apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes: 
        - name: log-storage
          emptyDir: {}
      containers:
        - name: writer
          image: hugonaing/log-writer:v1
          imagePullPolicy: Always
          volumeMounts:
            - name: log-storage
              mountPath: /usr/src/app/files

        - name: reader
          image: hugonaing/log-reader:v1
          imagePullPolicy: Always
          volumeMounts: 
            - name: log-storage
              mountPath: /usr/src/app/files
          ports: 
            - containerPort: 3000

